<a href="https://colab.research.google.com/github/Sushan9706/Concepts-and-Technologies-of-AI/blob/main/Sushan_Shrestha_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [1]:
import numpy as np
#1)
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)
print()
#2)
ones_array = np.ones((4, 2))
print("2. All ones 4x2 array:")
print(ones_array)
print()
#3)
filled_array = np.full((3, 3), 5)
print("3. Array filled with value 5:")
print(filled_array)
print()
#4)
sample_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(sample_array)
print("4. Zeros array with same shape as sample:")
print("Sample array:")
print(sample_array)
print("Zeros like array:")
print(zeros_like_array)
print()
#5)
ones_like_array = np.ones_like(sample_array)
print("5. Ones array with same shape as sample:")
print("Ones like array:")
print(ones_like_array)
print()
#6)
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. Converted list to numpy array:")
print("Original list:", new_list)
print("Numpy array:", numpy_array)

1. Empty 2x2 array:
[[9.57110031e-316 0.00000000e+000]
 [3.31971956e-316 9.35425436e-316]]

2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
[[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape as sample:
Sample array:
[[1 2]
 [3 4]]
Zeros like array:
[[0 0]
 [0 0]]

5. Ones array with same shape as sample:
Ones like array:
[[1 1]
 [1 1]]

6. Converted list to numpy array:
Original list: [1, 2, 3, 4]
Numpy array: [1 2 3 4]


Problem - 2: Array Manipulation:

 Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [2]:
#1)
arr1 = np.arange(10, 50)
print("1")
print(arr1)

#2)
arr2 = np.arange(9).reshape(3, 3)
print("2")
print(arr2)

#3)
identity_matrix = np.eye(3)
print("3")
print(identity_matrix)

#4)
random_arr = np.random.random(30)
mean_value = random_arr.mean()
print("4")
print(mean_value)

#5)
large_random = np.random.random((10, 10))
min_val = large_random.min()
max_val = large_random.max()
print("5")
print(f"Minimum: {min_val}, Maximum: {max_val}")

#6)
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("6")
print(zero_arr)

#7)
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7")
print(arr)
print(reversed_arr)

#8)
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("8")
print(border_arr)

#9)
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9")
print(checkerboard)

1
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2
[[0 1 2]
 [3 4 5]
 [6 7 8]]
3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4
0.4810345323456488
5
Minimum: 0.01545107624494213, Maximum: 0.9868070540673555
6
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
7
[1 2 0 0 4 0]
[0 4 0 0 2 1]
8
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
9
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [3]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#1)
add_result = x + y
print("1. Addition (x + y):")
print(add_result)
print()
#2)
sub_result = x - y
print("2. Subtraction (x - y):")
print(sub_result)
print()
#3)
multiply_result = x * 3
print("3. Multiplication (x * 3):")
print(multiply_result)
print()
#4)
square_result = x ** 2
print("4. Square of each element (x²):")
print(square_result)
print()
#5)
dot_vw = np.dot(v, w)
dot_xy = np.dot(x, y)
print("5. Dot products:")
print(f"Dot product of v and w: {dot_vw}")
print(f"Dot product of x and y:")
print(dot_xy)
print()
#6)
concat_row = np.concatenate((x, y), axis=0)
print("6. Concatenation:")
print("x and y concatenated along rows:")
print(concat_row)
v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_col = np.concatenate((v_col, w_col), axis=1)
print("v and w concatenated along columns:")
print(concat_col)
print()
#7)
print("7. Trying to concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v))
    print("Success:", concat_xv)
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: Cannot concatenate because x has shape (2, 2) and v has shape (2,).")
    print("They have different dimensions - x is 2D and v is 1D.")

1. Addition (x + y):
[[ 6  8]
 [10 13]]

2. Subtraction (x - y):
[[-4 -4]
 [-4 -3]]

3. Multiplication (x * 3):
[[ 3  6]
 [ 9 15]]

4. Square of each element (x²):
[[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation:
x and y concatenated along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated along columns:
[[ 9 11]
 [10 12]]

7. Trying to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Cannot concatenate because x has shape (2, 2) and v has shape (2,).
They have different dimensions - x is 2D and v is 1D.


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [4]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print()
#1)
print("1. Prove A.A^(-1) = I:")
try:
    A_inv = np.linalg.inv(A)
    identity_check = np.dot(A, A_inv)
    print("A inverse:")
    print(A_inv)
    print("A × A^(-1):")
    print(identity_check)
    print("This is approximately identity matrix I (with small rounding errors)")
except np.linalg.LinAlgError:
    print("Matrix A is singular, cannot compute inverse")
print()
#2)
print("2. Prove AB ≠ BA:")
AB = np.dot(A, B)
BA = np.dot(B, A)
print("A × B:")
print(AB)
print("B × A:")
print(BA)
print("Are they equal?", np.array_equal(AB, BA))
print()
#3)
print("3. Prove (AB)^T = B^T A^T:")
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("(AB)^T:")
print(AB_transpose)
print("B^T A^T:")
print(B_transpose_A_transpose)
print("Are they equal?", np.array_equal(AB_transpose, B_transpose_A_transpose))
print()


# Solving linear equations
print("Solving system of linear equations:")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")
A_coeff = np.array([[2, -3, 1],
                    [1, -1, 2],
                    [3, 1, -1]])
B_const = np.array([[-1], [-3], [9]])

print("\nCoefficient matrix A:")
print(A_coeff)
print("\nConstant matrix B:")
print(B_const)
try:
    A_inv_coeff = np.linalg.inv(A_coeff)
    X = np.dot(A_inv_coeff, B_const)
    print("\nSolution using inverse method:")
    print(f"x = {X[0][0]:.2f}")
    print(f"y = {X[1][0]:.2f}")
    print(f"z = {X[2][0]:.2f}")

    verification = np.dot(A_coeff, X)
    print("A × X should equal B:")
    print("A × X =", verification.flatten())
    print("B =", B_const.flatten())
except np.linalg.LinAlgError:
    print("Matrix is singular, cannot solve using inverse method")

Matrix A:
[[3 4]
 [7 8]]

Matrix B:
[[5 3]
 [2 1]]

1. Prove A.A^(-1) = I:
A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A × A^(-1):
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
This is approximately identity matrix I (with small rounding errors)

2. Prove AB ≠ BA:
A × B:
[[23 13]
 [51 29]]
B × A:
[[36 44]
 [13 16]]
Are they equal? False

3. Prove (AB)^T = B^T A^T:
(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]
Are they equal? True

Solving system of linear equations:
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

Coefficient matrix A:
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]

Constant matrix B:
[[-1]
 [-3]
 [ 9]]

Solution using inverse method:
x = 2.00
y = 1.00
z = -2.00
A × X should equal B:
A × X = [-1. -3.  9.]
B = [-1 -3  9]
